version: 0.2

phases:
  install:
    on-failure: ABORT | CONTINUE
    commands:
      - echo Install ...
      - apt install nginx -y
  pre_build:
    on-failure: ABORT | CONTINUE
    commands:
      - echo Login in to ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    on-failure: ABORT | CONTINUE
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    on-failure: ABORT | CONTINUE
    commands:
      - echo Build started on `date`
      - echo Pushing the Docker images...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG