version: 0.2
phases:
  pre_build:
    on-failure: ABORT | CONTINUE
    commands:
      - echo Login in to ECR...
      - export AWS_ACCOUNT_ID=049115486379
      - export IMAGE_REPO_NAME=front_taiga
      - export IMAGE_TAG=latest
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 049115486379.dkr.ecr.eu-north-1.amazonaws.com
  build:
    on-failure: ABORT | CONTINUE
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    on-failure: ABORT | CONTINUE
    commands:
      - echo Build started on `date`
      - echo Pushing the Docker images...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
